package cargo

import (
	"os"
	"path/filepath"
	"testing"
)

const sampleLock = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.196"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "870026e60fa08c69f064aa766c10f10b1d62db9ccd4d0abb206472bee0ce3b32"

[[package]]
name = "tokio"
version = "1.36.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "my-app"
version = "0.1.0"
dependencies = ["serde", "tokio"]
`

func writeLock(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "Cargo.lock")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestCollectParsesRegistryPackages(t *testing.T) {
	records, err := New(writeLock(t, sampleLock)).Collect()
	if err != nil {
		t.Fatalf("Collect() error = %v", err)
	}
	// my-app has no source: it's the workspace crate itself, not a dep.
	if len(records) != 2 {
		t.Fatalf("Collect() = %d records, want 2 (workspace crate skipped)", len(records))
	}

	got := map[string]string{}
	for _, r := range records {
		if eco := r.Payload["ecosystem"]; eco != "crates.io" {
			t.Errorf("ecosystem = %v, want crates.io", eco)
		}
		got[r.Payload["name"].(string)] = r.Payload["version"].(string)
	}
	if got["serde"] != "1.0.196" || got["tokio"] != "1.36.0" {
		t.Errorf("parsed packages = %v, want serde 1.0.196 and tokio 1.36.0", got)
	}
}

func TestCollectMissingFileErrors(t *testing.T) {
	if _, err := New(filepath.Join(t.TempDir(), "Cargo.lock")).Collect(); err == nil {
		t.Fatal("Collect() error = nil, want read error")
	}
}

func TestCollectMalformedTOMLErrors(t *testing.T) {
	if _, err := New(writeLock(t, "[[package\nname=")).Collect(); err == nil {
		t.Fatal("Collect() error = nil, want parse error")
	}
}
